"""Strengthen deal-activity relationship

Revision ID: 149eeca48b0b
Revises: 94a82de8dd2c
Create Date: 2025-08-05 02:49:56.114255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149eeca48b0b'
down_revision: Union[str, Sequence[str], None] = '94a82de8dd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
