"""Add new columns to companies table

Revision ID: 6fe9c012bdc8
Revises: 9bdb6f109379
Create Date: 2025-06-25 07:14:48.725241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe9c012bdc8'
down_revision: Union[str, Sequence[str], None] = '9bdb6f109379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_kana', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('other_details', sa.JSON(), nullable=True))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('companies', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['company_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=True)
    op.alter_column('companies', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'other_details')
    op.drop_column('companies', 'company_kana')
    # ### end Alembic commands ###
