"""Add agency_id to deals

Revision ID: 949f58a2de8b
Revises: cf5ba5ad051b
Create Date: 2025-08-04 09:21:54.782152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949f58a2de8b'
down_revision: Union[str, Sequence[str], None] = 'cf5ba5ad051b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('agency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deals', 'agencies', ['agency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'agency_id')
    # ### end Alembic commands ###
